application: lookatmesnowboii
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /css
  static_dir: bootstrap/css

- url: /js
  static_dir: bootstrap/js

- url: /img
  static_dir: bootstrap/img

- url: /.*
  script: lookatme.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest